[package]
name = "upgrader_canister_client"
version.workspace = true
edition.workspace = true

[dependencies]
upgrader_canister_did = { workspace = true }

candid = { workspace = true }
ic-canister-client = { workspace = true }
